### ISSUE TITLE
Make the veins biome dependent

### ISSUE THREAD

**Issue by murilorodelli** [zehmaria/resourcefullveins#1]
I'm trying to make the ore vein be rare and biome dependent. But after various experiments with biometag and chance parameter it is not generating. The only config that seems to generate veins is "minecraft:is_overworld"

Even after trying other tags like: "forge:is_plains", "minecraft:is_plains", "forge:plains", it don't generate as expected

Version: resourcefullveins-forge-1.19.2-230605T20

example config I'm trying
==================

#List of diet groups
[[veins]]
resource = "minecraft:iron_ore"
deepslate = "minecraft:deepslate_iron_ore"
extraRadius = 0
extraDeltaRadius = 0
chance = 10
biometag = "minecraft:plains"

[[veins]]
resource = "minecraft:copper_ore"
deepslate = "minecraft:deepslate_copper_ore"
extraRadius = 0
extraDeltaRadius = 0
chance = 10
biometag = "minecraft:meadow"

[[veins]]
resource = "minecraft:coal_ore"
deepslate = "minecraft:deepslate_coal_ore"
extraRadius = 2
extraDeltaRadius = 2
chance = 20
biometag = "minecraft:taiga"

**Comment by zehmaria** [comment]
yeah, it requires biome tags specifically. but since you mentioned that even that doesn't work, I will have a look.

**Comment by zehmaria** [comment]
I rewrote the bits since the project was quite a mess in my end. And finished what I was intending to do back then. The mod is now fully using datapacks. You can control a lot more between using forge/biome_modifier, worldgen/configured_feature, and worldgen/placed_feature. Such thing has also been implemented on both versions available. 

For biome filtering, I tested it on my end by changing the default resourcefullveins:biome_tag in one of the veins, inside worldgen/configured_feature/vein_selector.json, to minecraft:is_savanna. And that worked.  

If you are going to use it like that, make sure the resourcefullveins:biome_tag is indeed an exiting tag. For now, that can only accept that. 

For biome_modifier, you can see https://github.com/vectorwing/FarmersDelight/blob/1.20/src/main/resources/data/farmersdelight/forge/biome_modifier/wild_onions.json to see a bit more what can be done with add_features_by_filter. If you decide to expand in that direction. 

If you wish to do distinct veins to singular biomes, using biome_modifier is likely your best bet. You make a modifier for every vein you want. You set the biome filtering there and then make a simple feature pair for the ore in question [configured_feature/gold_ore.json and placed_feature/gold_ore.json] with whatever rarity you wish to see defined in the placed_feature. No need to use minecraft:random_selector and whatever I use by default, as that will only make fine-tuning rarity in your case a headache.

**Comment by murilorodelli** [comment]
Marvelous. I will test ASAP. Thank you very much. I love all your mods and concepts

ps; Zé Maria, are you Brazillian or Portuguese, BTW? I'm br

**Comment by zehmaria** [comment]
Br  :P

**Comment by murilorodelli** [comment]
I'm testing right now with Tectonic as terrain generator. My goal is to have a survival/realistic/semi-tfc modpack with in world veins to process with create resembling https://www.curseforge.com/minecraft/modpacks/manufactio modpack.

**Comment by zehmaria** [comment]
that is why I made it too, good luck with your pack.

**Comment by murilorodelli** [comment]
Do you have a pack for reference? What loader are you using? Paxi? KubeJS? I should maintain resourcefullveins as datapack name right? sorry for newbie questions, I only used to make modpacks for 1.12.2 and 1.7.10

**Comment by zehmaria** [comment]
I used the really old version on my pack where it didn't use features much, was still stuck with a config, and it was really a simplistic use too. So, it won't be useful for you. I will likely use the new version in 1.20.4 or 1.21.
