### ISSUE TITLE
Make configured feature more flexible to block replacement

### ISSUE THREAD

**Issue by murilorodelli** [zehmaria/resourcefullveins#2]
I'm planning to use this mod alongside spelunkery (https://www.curseforge.com/minecraft/mc-mods/spelunkery) and similar mods that generates ores in more blocks than stone and deepslate. It would be nice to have more options for replacement othen than replace_stone and replace_deepslate and have is more like a dictionary.

The ore vein should ideally make replacement based on the stone it being generated or use stone/deepslate if air depending on the Y level

**Comment by zehmaria** [comment]
The mod already uses the vanilla tags minecraft:stone_ore_replaceables and minecraft:deepslate_ore_replaceables. So, depending on the mod, that should cover it.  It is just that I hard coded it instead of using targets like minecraft:ore feature does and many others modded features based on it. Which would allow even more configuration.

I was looking at create layered ore and mekanism resizable ore features, checking what could be improved. And that is what I was going to do next, so next update that should be covered.

**Comment by zehmaria** [comment]
This has been added as of 0.2.0. To explain what is custom and what is not, I commented this file https://github.com/zehmaria/peaks/blob/mc1.20.1/dev/src/main/resources/data/peaks/worldgen/configured_feature/ore_vein_coal.json 

For this issue in particular, the requested is stuff is in "targets": [ 

But, like with vanilla's ore gen, you will need to add the custom stuff for the modded stone layers yourself, using their tags for target and their blocks for replacement.
